# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
 name:Default

steps:
- script:echo Hello,world!
displayName:'run a one-line script'
- script:mvn clean install
displayName:'bulid a maven'
- script:java -jar target/MavenApp109-1.0-SNAPSHOT.jar
displayName:'running maven'
